# Assignment 3
## Task 1
**1.1 : Write a function to compute 5/0 and use try/except to catch the exceptions.**

In [20]:
def division(a,b):
    try:
        c = a/b
        return c 
    except ZeroDivisionError:
        return "Divide by Zero Error"
    
x1=int(input("Enter the Divident: "))
y1=int(input("Enter the Divisor: "))

z1= division(x1,y1)
print("Quotient is: {}".format(z1))

Enter the Divident:  55
Enter the Divisor:  15


Quotient is: 3.6666666666666665


In [21]:
x2=int(input("Enter the Divident: "))
y2=int(input("Enter the Divisor: "))
z2= division(x2,y2)
print("Quotient is: {}".format(z2))

Enter the Divident:  5
Enter the Divisor:  0


Quotient is: Divide by Zero Error


**1.2 : Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].**
</br>
**Output should come as below:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.**

In [22]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print("{} {} {}.".format(i,j,k))

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2

**1 . Write a function so that the columns of the output matrix are powers of the input vector.**
</br>**The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.**

In [23]:
import numpy as np

def vandermonde(vector,N=None,increasing=False) :
    vector_arr = np.asarray(vector)
    if N is None:
        N = len(vector_arr)
    power = len(vector_arr)
    tmp = np.empty((power, N), dtype=int)
    for i in range(0,power):
        for j in range(0,N):
            tmp[i][j] = (vector_arr[i]**(N-1-j))
    matrix = tmp[:, ::-1] if increasing else tmp         
    return np.asarray(matrix)

v = [1 , 3 , 5 , 2]
mat_vf=vandermonde(v,3)
mat_vf

array([[ 1,  1,  1],
       [ 9,  3,  1],
       [25,  5,  1],
       [ 4,  2,  1]])

In [24]:
mat_vt=vandermonde(v,5,increasing=True)
mat_vt

array([[  1,   1,   1,   1,   1],
       [  1,   3,   9,  27,  81],
       [  1,   5,  25, 125, 625],
       [  1,   2,   4,   8,  16]])

In [25]:
mat_vnt=vandermonde(v,8,increasing=True)
mat_vnt

array([[    1,     1,     1,     1,     1,     1,     1,     1],
       [    1,     3,     9,    27,    81,   243,   729,  2187],
       [    1,     5,    25,   125,   625,  3125, 15625, 78125],
       [    1,     2,     4,     8,    16,    32,    64,   128]])

In [26]:
mat_vnf=vandermonde(v,0)
mat_vnf

array([], shape=(4, 0), dtype=int32)